#include <iostream>
#include <string>
#include <vector>
#include <float.h>
#include <random>
#include <fstream>
#include <sstream>
#include <chrono>
#include <algorithm>
#include "misc.cpp"
#include "hyperparams.cpp"
#include "Network.h"
